# Generated by Django 4.2.2 on 2023-08-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
