# Generated by Django 4.2.2 on 2023-08-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='auctions.listing'),
        ),
    ]
