# Generated by Django 4.2.2 on 2023-09-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
