# Generated by Django 4.2.2 on 2023-10-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_is_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
